name: aws-lb-controller
title: AWS Load Balancer controller
type: infrastructure
icon: aws-lb-controller
scalable: false
hostname: eks-lb-controller
containers:
  - name: aws-load-balancer-controller

certs:
- name: webhook
  days: 36500
  key:
    type: rsa
    length: 4096
  helm:
    cert: webhookTLS.cert
    key: webhookTLS.key
    ca: webhookTLS.caCert

helm:
  name: eks
  source: https://aws.github.io/eks-charts
  chart: eks/aws-load-balancer-controller
  version: 1.9.0
  configurations:
  - name: aws-lb-controller
    annotations: deploymentAnnotations
    labels: podLabels
    resources: resources    
  values: 
  - name: clusterName
    value: "{{kubernetes.externalID}}"
  - name: serviceAccount.annotations
    value:
      eks.amazonaws.com/role-arn: "{{wodby_eks_lb_controller_role_arn}}"
