name: aws-lb-controller
title: AWS Load Balancer controller
type: infrastructure
icon: aws-lb-controller
scalable: false
certs:
- name: webhook
  days: 36500
  key:
    type: rsa
    length: 4096
  dns:
  - aws-load-balancer-webhook-service.{{service.name}}.svc
  - aws-load-balancer-webhook-service.{{service.name}}.svc.cluster.local
  helm:
    cert: webhookTLS.cert
    key: webhookTLS.key
    ca: webhookTLS.caCert

helm:
  name: eks
  source: https://aws.github.io/eks-charts
  chart: eks/aws-load-balancer-controller
  version: 1.9.0
  values:
  - name: clusterName
    value: "{{kubernetes.externalID}}"
  - name: serviceAccount.annotations
    value:
      eks.amazonaws.com/role-arn: "{{wodby_eks_lb_controller_role_arn}}"
workloads:
- id: main
  kind: deployment
  primary: true
  containers:
  - name: aws-load-balancer-controller

    helm:
      resources: resources
  helm:
    labels: podLabels
    annotations: deploymentAnnotations
